### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by NISH1001** [bewakes/justproofs#1]
I like the idea. Cool. I want to contribute on this.

**Comment by bewakes** [comment]
Cool man. I'll first set up the project properly and will notify you. Its just a django project though.

**Comment by NISH1001** [comment]
@bewakes Cool.... The project seems cool. Let's make it as awesome as we are.

**Comment by bewakes** [comment]
Yup. Lets..

**Comment by NISH1001** [comment]
looking forward to...
